server:
  port: 8501
spring:
  profiles:
    active: dev
  application:
    name: weiran-oauth2-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
